title: ‘’BIOGRAFIA‘’

email: ‘’Urbinael088@gmail.com‘’
description: ‘’Proyecto,biografia de mi vida‘’
favicon: 5626549035
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/GaelU28/GaelU28.github.io.git
  

navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Brandon Gael
        link: ./index.html#small-image
  - name: Bienvenido
    link: ./another-page.html
